### ISSUE TITLE
Chapter author formatting / ORCiD links

### ISSUE THREAD

**Issue by oneilsh** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#202]
I think we may have lost some formatting on the author lists for each chapter, we used to have ORCiD links and such right?

**Comment by chrisroederucdenver** [comment]
Using quarto 1.4.549 on macos commandline, at the root of the project, with this change I get: 
`[ 1/16] index.qmd
WARNING: One or more extensions have been built in to Quarto. Please use the following command to remove the unneeded extension:
  quarto remove extension quarto-ext/lightbox
ERROR: Template partial /Users/roederc/work/git_n3c/guide-to-n3c-v1/title-block.html was not found. Please confirm that the path to the file is correct.

Stack trace:
    at file:///Applications/quarto/bin/quarto.js:41490:19
    at Array.flatMap (<anonymous>)
    at readPartials (file:///Applications/quarto/bin/quarto.js:41484:20)
    at runPandoc (file:///Applications/quarto/bin/quarto.js:68839:30)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async renderPandoc (file:///Applications/quarto/bin/quarto.js:70041:26)
    at async Object.onRender (file:///Applications/quarto/bin/quarto.js:91500:42)
    at async renderFileInternal (file:///Applications/quarto/bin/quarto.js:77238:17)
    at async renderFiles (file:///Applications/quarto/bin/quarto.js:77062:17)
    at async renderProject (file:///Applications/quarto/bin/quarto.js:77389:25)
`
